[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "http://64.23.130.230:8420/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/rfpapi/*"
  to = "http://64.23.130.230:8421/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200